version: '3.7'


services:

  sage-ecr:
    image: sagecontinuum/sage-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}:/usr/src/app  # for development only
    env_file: mysql.env
    environment:
      DISABLE_AUTH: 1
      tokenInfoEndpoint: ${SageTokenInfoEndpoint} 
      tokenInfoUser: ${SageTokenInfoUser}  
      tokenInfoPassword: ${SageTokenInfoPassword} 
    


  db:
    image: mysql:8.0.20
    env_file: mysql.env
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - sage-ecr-db:/var/lib/mysql

volumes:
  sage-ecr-db:
  
    
