version: '3.7'


services:

  sage-api:
    image: sagecontinuum/sage-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}:/usr/src/app  # for development only
    env_file: mysql.env
    
    


  db:
    image: mysql:8
    env_file: mysql.env
   
    volumes:
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - sage-ecr-db:/var/lib/mysql

volumes:
  sage-ecr-db:
  
    
