apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  
  - ecr-api.deployment
  - ecr-api.ingress
  - ecr-api.secret
  - ecr-api.service

  - ecr-db.deployment
  - ecr-db.secret
  - ecr-db.service
  - ecr-db-local.pvc

  - ecr-jenkins.config
  - ecr-jenkins-casc.secret
  - ecr-jenkins.deployment
  - ecr-jenkins.service
  #- ecr-jenkins-local.pvc  
  # was giving me
  # WARNING	j.branch.WorkspaceLocatorImpl#getWorkspaceRoot: JENKINS-2111 path sanitization ineffective when using legacy Workspace Root Directory ‘${ITEM_ROOTDIR}/workspace’; switch to ‘${JENKINS_HOME}/workspace/${ITEM_FULL_NAME}’ as in JENKINS-8446 / JENKINS-21942

  