
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Start docker-compose
      run: docker-compose up -d

    - name: wait for service
      run: |
        sleep 5
        docker-compose -v
        docker exec -t sage-ecr_sage-ecr_1 printenv
        while [[ ${HEALTH}_ != "ok_" ]] ; do HEALTH=$(curl -s http://localhost:5000/healthy) ; echo $HEALTH ; sleep 1 ; done

    - name: run tests
      run: docker exec -t sage-ecr_sage-ecr_1 pytest -v
