
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: run tests
      run: docker-compose run --rm  sage-ecr  coverage run -m pytest -v

    - name: test code coverage
      run: docker-compose run --rm  sage-ecr  coverage report -m
