
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug info
      run: docker volume ls

    - name: Build the Docker image
      run: docker-compose build

    - name: Start docker-compose
      run: docker-compose up -d

    - name: wait for service
      run: |
        set +e 
        while [[ ${HEALTH}_ != "ok_" ]] ; do HEALTH=$(curl -s http://localhost:5000/healthy) ; echo $HEALTH ; sleep 1 ; done

    - name: run tests
      run: docker exec -t sage-ecr_sage-ecr_1 pytest -v
