
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Start docker-compose
      run: docker-compose up -d

    - name: wait for service
      run: while [[ $(curl -s http://localhost:5000/healthy) != "ok" ]] ; do echo "no connection..." ; sleep 1 ; done

    - name: run tests
      run: docker exec -t sage-ecr_sage-ecr_1 pytest -v
